#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
---
apiVersion: batch/v1
kind: Job
metadata:
  name: anagrams
spec:
  template:
    spec:
      containers:
      - name: anagrams
        image: academiaonline/anagrams:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: data
          mountPath: /words.txt
          readOnly: true
          subPath: words.txt
      volumes:
      - name: data
        hostPath:
          path: /tmp/words.txt
          type: File
---
